# Generated by Django 4.2.29 on 2026-03-29 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Department this employee belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="security.department",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="roles",
            field=models.ManyToManyField(
                blank=True, help_text="Roles assigned to this employee", related_name="employees", to="security.role"
            ),
        ),
    ]
