# Generated by Django 4.2.29 on 2026-04-05 13:58

from django.db import migrations, models
from django.utils.text import slugify


def generate_employee_slugs(apps, schema_editor):
    """Auto-generate slugs for existing employees."""
    Employee = apps.get_model("accounts", "Employee")
    for employee in Employee.objects.all():
        if employee.first_name and employee.last_name:
            base_slug = slugify(f"{employee.first_name}-{employee.last_name}")
        else:
            base_slug = slugify(employee.email.split("@")[0])

        if not base_slug:
            base_slug = slugify(employee.email.replace("@", "-").replace(".", "-"))

        slug = base_slug
        counter = 1
        while Employee.objects.filter(slug=slug).exclude(pk=employee.pk).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1

        employee.slug = slug
        employee.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_employee_department_employee_roles"),
    ]

    operations = [
        # Step A: Add the slug field as nullable and non-unique
        migrations.AddField(
            model_name="employee",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly identifier. Auto-generated from name or email.",
                max_length=150,
                null=True,
                verbose_name="Slug",
            ),
        ),
        # Step B: Populate slugs for existing employees
        migrations.RunPython(generate_employee_slugs, migrations.RunPython.noop),
        # Step C-1: Make the field non-nullable (but not yet unique)
        migrations.AlterField(
            model_name="employee",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly identifier. Auto-generated from name or email.",
                max_length=150,
                verbose_name="Slug",
            ),
        ),
        # Step C-2: Add unique constraint via RunSQL to avoid Django's double-index bug
        migrations.RunSQL(
            sql="ALTER TABLE employees ADD CONSTRAINT employees_slug_unique UNIQUE (slug)",
            reverse_sql="ALTER TABLE employees DROP CONSTRAINT IF EXISTS employees_slug_unique",
        ),
        # Step C-3: Update model state to reflect uniqueness (no database operation)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="employee",
                    name="slug",
                    field=models.SlugField(
                        blank=True,
                        help_text="URL-friendly identifier. Auto-generated from name or email.",
                        max_length=150,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
