# Generated by Django 4.2.29 on 2026-04-20 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date/time when the record was created"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, help_text="Date/time when the record was last modified"),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("inventory_valuation", "Inventory Valuation"),
                            ("sales_summary", "Sales Summary"),
                            ("stock_movement", "Stock Movement"),
                        ],
                        help_text="Type of report to generate",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Current status of the report job",
                        max_length=20,
                    ),
                ),
                (
                    "result_file",
                    models.FileField(
                        blank=True, help_text="Generated report file (CSV/PDF)", null=True, upload_to="reports/"
                    ),
                ),
                ("error_message", models.TextField(blank=True, help_text="Error message if job failed", null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        help_text="User who requested the report",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["actor", "created_at"], name="reporting_r_actor_i_49f00e_idx"),
                    models.Index(fields=["status", "created_at"], name="reporting_r_status_595e49_idx"),
                ],
            },
        ),
    ]
