# Generated by Django 4.2.29 on 2026-03-31 11:24

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date/time when the record was created"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, help_text="Date/time when the record was last modified"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, help_text="Date/time when the record was soft-deleted", null=True),
                ),
                (
                    "name",
                    models.CharField(help_text="Category name (e.g., 'Major Appliances')", max_length=100, unique=True),
                ),
                (
                    "code",
                    models.SlugField(
                        blank=True, help_text="Auto-generated slug code (e.g., 'major-appliances')", unique=True
                    ),
                ),
                ("description", models.TextField(blank=True, help_text="Category description", null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent category (for hierarchical structure)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="inventory.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "db_table": "inventory_categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date/time when the record was created"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, help_text="Date/time when the record was last modified"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, help_text="Date/time when the record was soft-deleted", null=True),
                ),
                (
                    "sku",
                    models.CharField(
                        help_text="Unique SKU code (e.g., 'WM-CR-159' for Washing Machine Crazy 159)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Product name", max_length=200)),
                (
                    "unit_of_measure",
                    models.CharField(
                        choices=[
                            ("pcs", "Pieces"),
                            ("kg", "Kilograms"),
                            ("g", "Grams"),
                            ("l", "Liters"),
                            ("ml", "Milliliters"),
                            ("m", "Meters"),
                            ("cm", "Centimeters"),
                            ("box", "Boxes"),
                            ("pack", "Packs"),
                        ],
                        default="pcs",
                        help_text="Unit of measure for this product",
                        max_length=10,
                    ),
                ),
                (
                    "current_stock",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        editable=False,
                        help_text="Current stock quantity (controlled by operations layer)",
                        max_digits=19,
                    ),
                ),
                (
                    "wac_price",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        editable=False,
                        help_text="Weighted Average Cost price (19,4 precision)",
                        max_digits=19,
                    ),
                ),
                ("description", models.TextField(blank=True, help_text="Product description", null=True)),
                (
                    "location_note",
                    models.CharField(
                        blank=True,
                        help_text="Storage location note (e.g., 'Warehouse A, Shelf 5')",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Product category",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="inventory.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "inventory_products",
                "ordering": ["sku"],
            },
        ),
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("INTAKE", "Stock Intake (Purchase)"),
                            ("ADJUST_ADD", "Manual Add (Correction)"),
                            ("ADJUST_REDUCE", "Manual Reduce (Correction)"),
                            ("SALE", "Sale Order Deduction"),
                            ("PURCHASE", "Purchase Order Receipt"),
                            ("TRANSFER", "Warehouse Transfer"),
                            ("RETURN", "Customer Return"),
                            ("DAMAGE", "Damage/Loss Write-off"),
                        ],
                        help_text="Type of stock change",
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Quantity changed (positive for in, negative for out)",
                        max_digits=19,
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Unit cost for this transaction (for WAC calculation)",
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "balance_before",
                    models.DecimalField(
                        decimal_places=4, help_text="Stock balance before this transaction", max_digits=19
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=4, help_text="Stock balance after this transaction", max_digits=19
                    ),
                ),
                (
                    "wac_before",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="WAC price before this transaction",
                        max_digits=19,
                    ),
                ),
                (
                    "wac_after",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="WAC price after this transaction",
                        max_digits=19,
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of reference document (e.g., 'PurchaseOrder', 'SalesOrder')",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(blank=True, help_text="ID of reference document", max_length=50, null=True),
                ),
                (
                    "location_note",
                    models.CharField(
                        blank=True,
                        help_text="Storage location (if different from product default)",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="Transaction timestamp")),
                ("notes", models.TextField(blank=True, help_text="Additional notes about this transaction", null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Employee who created this transaction",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product affected by this transaction",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_transactions",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Transaction",
                "verbose_name_plural": "Stock Transactions",
                "db_table": "inventory_stock_transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["product", "-created_at"], name="inventory_s_product_a59faf_idx"),
                    models.Index(fields=["change_type", "-created_at"], name="inventory_s_change__a06ffc_idx"),
                    models.Index(fields=["reference_type", "reference_id"], name="inventory_s_referen_b22c22_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="StockAdjustment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date/time when the record was created"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, help_text="Date/time when the record was last modified"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, help_text="Date/time when the record was soft-deleted", null=True),
                ),
                (
                    "old_quantity",
                    models.DecimalField(
                        decimal_places=4, help_text="Current stock quantity before adjustment", max_digits=19
                    ),
                ),
                (
                    "new_quantity",
                    models.DecimalField(
                        decimal_places=4, help_text="Target stock quantity after adjustment", max_digits=19
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("DAMAGE", "Damage/Loss"),
                            ("FOUND", "Stock Found"),
                            ("CORRECTION", "Inventory Correction"),
                            ("EXPIRY", "Expiry Write-off"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Reason for adjustment",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("EXECUTED", "Executed"),
                        ],
                        default="PENDING",
                        help_text="Adjustment status",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True, help_text="Request timestamp")),
                ("approved_at", models.DateTimeField(blank=True, help_text="Approval timestamp", null=True)),
                (
                    "executed_at",
                    models.DateTimeField(
                        blank=True, help_text="Execution timestamp (when transaction was created)", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes about the adjustment", null=True)),
                (
                    "location_note",
                    models.CharField(blank=True, help_text="Storage location note", max_length=200, null=True),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Employee who approved the adjustment",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product to adjust",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="inventory.product",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        help_text="Employee who requested the adjustment",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustment_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Adjustment",
                "verbose_name_plural": "Stock Adjustments",
                "db_table": "inventory_stock_adjustments",
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(fields=["status", "-requested_at"], name="inventory_s_status_71fc73_idx"),
                    models.Index(fields=["product", "status"], name="inventory_s_product_55154b_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["sku"], name="inventory_p_sku_3b9fee_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["category", "sku"], name="inventory_p_categor_70e263_idx"),
        ),
    ]
