# Generated by Django 4.2.29 on 2026-03-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockadjustment",
            name="rejection_comment",
            field=models.TextField(
                blank=True, help_text="Required comment when rejecting adjustment (explains why)", null=True
            ),
        ),
    ]
