# Generated by Django 4.2.29 on 2026-04-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_slug_unique_and_remove_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, help_text="URL-friendly slug (e.g., 'major-appliances')", unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, help_text="URL-friendly slug (e.g., 'wm-cr-159')", unique=True),
        ),
    ]
