# Generated by Django 4.2.29 on 2026-03-29 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent department (for hierarchical structure)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="security.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "db_table": "security_departments",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True, help_text="What this policy permits or denies")),
                (
                    "effect",
                    models.CharField(
                        choices=[("allow", "Allow"), ("deny", "Deny")],
                        default="allow",
                        help_text="Allow or Deny this action",
                        max_length=10,
                    ),
                ),
                (
                    "resource",
                    models.CharField(help_text="Resource pattern (e.g., inventory.*, sales.order.*)", max_length=100),
                ),
                (
                    "action",
                    models.CharField(help_text="Action pattern (e.g., create, read, update, delete)", max_length=100),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Policy",
                "verbose_name_plural": "Policies",
                "db_table": "security_policies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("code", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        help_text="Department this role belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="security.department",
                    ),
                ),
                (
                    "policies",
                    models.ManyToManyField(
                        help_text="Policies granted by this role", related_name="roles", to="security.policy"
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "db_table": "security_roles",
                "ordering": ["department__name", "name"],
                "unique_together": {("department", "name")},
            },
        ),
    ]
