# Generated by Django 4.2.29 on 2026-03-29 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "actor_email",
                    models.EmailField(blank=True, help_text="Email backup (in case user is deleted)", max_length=254),
                ),
                (
                    "actor_name",
                    models.CharField(blank=True, help_text="Name backup (in case user is deleted)", max_length=200),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("read", "Read"),
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("adjust", "Adjust"),
                            ("transfer", "Transfer"),
                            ("other", "Other"),
                        ],
                        help_text="Type of action performed",
                        max_length=50,
                    ),
                ),
                (
                    "action_code",
                    models.CharField(
                        help_text="Machine-readable action code (e.g., inventory.stock.adjust)", max_length=100
                    ),
                ),
                (
                    "action_description",
                    models.TextField(blank=True, help_text="Human-readable description of the action"),
                ),
                (
                    "content_type",
                    models.CharField(help_text="Type of object affected (e.g., inventory.Product)", max_length=100),
                ),
                ("object_id", models.CharField(help_text="ID of the object affected", max_length=100)),
                ("object_repr", models.CharField(help_text="String representation of the object", max_length=300)),
                (
                    "before_data",
                    models.JSONField(blank=True, help_text="State before the change (for updates/deletes)", null=True),
                ),
                (
                    "after_data",
                    models.JSONField(blank=True, help_text="State after the change (for creates/updates)", null=True),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, help_text="When the action occurred")),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, help_text="IP address of the request", null=True),
                ),
                ("user_agent", models.TextField(blank=True, help_text="User agent string from request")),
                ("extra_data", models.JSONField(blank=True, help_text="Additional context-specific data", null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Employee who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["-timestamp"], name="audit_logs_timesta_e93820_idx"),
                    models.Index(fields=["actor", "-timestamp"], name="audit_logs_actor_i_9ecce2_idx"),
                    models.Index(fields=["content_type", "object_id"], name="audit_logs_content_4392a4_idx"),
                    models.Index(fields=["action", "-timestamp"], name="audit_logs_action_f48619_idx"),
                ],
            },
        ),
    ]
