# Generated by Django 4.2.29 on 2026-03-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="user_agent",
            field=models.TextField(blank=True, help_text="User agent string from request", null=True),
        ),
    ]
