# Generated by Django 4.2.29 on 2026-04-03 03:43

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0002_stockadjustment_rejection_comment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, help_text="Date/time when the record was last modified"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, help_text="Date/time when the record was soft-deleted", null=True),
                ),
                (
                    "po_number",
                    models.CharField(
                        editable=False,
                        help_text="Atomic unique PO number (format: PO-00001)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "supplier_info_snapshot",
                    models.JSONField(blank=True, help_text="Supplier info copied at order confirmation", null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ISSUED", "Issued"),
                            ("IN_PROGRESS", "In-Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        help_text="PO status (Draft -> Issued -> In-Progress -> Completed -> Cancelled)",
                        max_length=20,
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        editable=False,
                        help_text="Total cost of all line items",
                        max_digits=19,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="PO creation timestamp")),
                ("issued_at", models.DateTimeField(blank=True, help_text="PO issued timestamp", null=True)),
                ("completed_at", models.DateTimeField(blank=True, help_text="PO completed timestamp", null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, help_text="PO cancelled timestamp", null=True)),
                ("notes", models.TextField(blank=True, help_text="Internal notes about this PO", null=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Employee who cancelled this PO",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders_cancelled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Employee who completed this PO",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders_completed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Employee who created this PO",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Employee who issued this PO",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Order",
                "verbose_name_plural": "Purchase Orders",
                "db_table": "purchasing_orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupplierCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date/time when the record was created"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, help_text="Date/time when the record was last modified"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, help_text="Date/time when the record was soft-deleted", null=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name (e.g., 'Raw Materials', 'Electronics')", max_length=100, unique=True
                    ),
                ),
                ("code", models.SlugField(blank=True, help_text="Auto-generated slug code", unique=True)),
                ("description", models.TextField(blank=True, help_text="Category description", null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent category (for hierarchical structure)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="purchasing.suppliercategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Category",
                "verbose_name_plural": "Supplier Categories",
                "db_table": "purchasing_supplier_categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date/time when the record was created"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, help_text="Date/time when the record was last modified"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, help_text="Date/time when the record was soft-deleted", null=True),
                ),
                ("name", models.CharField(help_text="Supplier name (individual or company)", max_length=200)),
                ("email", models.EmailField(blank=True, help_text="Supplier email address", max_length=254)),
                ("phone", models.CharField(blank=True, help_text="Supplier phone number", max_length=20)),
                ("address", models.TextField(blank=True, help_text="Supplier physical address")),
                (
                    "contact_person",
                    models.CharField(blank=True, help_text="Primary contact person name", max_length=200),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes about this supplier", null=True)),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Supplier category",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="suppliers",
                        to="purchasing.suppliercategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
                "db_table": "purchasing_suppliers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date/time when the record was created"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, help_text="Date/time when the record was last modified"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, help_text="Date/time when the record was soft-deleted", null=True),
                ),
                ("quantity", models.DecimalField(decimal_places=4, help_text="Quantity ordered", max_digits=19)),
                (
                    "received_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Quantity received so far (for partial receiving)",
                        max_digits=19,
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=4, help_text="Unit cost from supplier (19,4 precision)", max_digits=19
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        editable=False,
                        help_text="Line total (quantity * unit_cost)",
                        max_digits=19,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Parent purchase order",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="purchasing.purchaseorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product being ordered",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_order_items",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Order Item",
                "verbose_name_plural": "Purchase Order Items",
                "db_table": "purchasing_order_items",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="supplier",
            field=models.ForeignKey(
                help_text="Supplier for this purchase order",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_orders",
                to="purchasing.supplier",
            ),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(fields=["name"], name="purchasing__name_a7f50a_idx"),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(fields=["email"], name="purchasing__email_45ba6c_idx"),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(fields=["category", "name"], name="purchasing__categor_6fae8a_idx"),
        ),
        migrations.AddIndex(
            model_name="purchaseorderitem",
            index=models.Index(fields=["order", "product"], name="purchasing__order_i_7f8cb9_idx"),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(fields=["po_number"], name="purchasing__po_numb_6c26ea_idx"),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(fields=["supplier", "-created_at"], name="purchasing__supplie_73e19b_idx"),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(fields=["status", "-created_at"], name="purchasing__status_21faff_idx"),
        ),
    ]
