# Generated by Django 4.2.29 on 2026-04-01 17:31

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0002_stockadjustment_rejection_comment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date/time when the record was created"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, help_text="Date/time when the record was last modified"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, help_text="Date/time when the record was soft-deleted", null=True),
                ),
                ("name", models.CharField(help_text="Customer name (individual or company)", max_length=200)),
                ("email", models.EmailField(blank=True, help_text="Customer email address", max_length=254)),
                ("phone", models.CharField(blank=True, help_text="Customer phone number", max_length=20)),
                (
                    "shipping_address",
                    models.TextField(
                        blank=True, help_text="Default shipping address (snapshotted to SalesOrder at order time)"
                    ),
                ),
                (
                    "billing_address",
                    models.TextField(blank=True, help_text="Billing address (if different from shipping)"),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes about this customer", null=True)),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "db_table": "sales_customers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SalesOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, help_text="Date/time when the record was last modified"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, help_text="Date/time when the record was soft-deleted", null=True),
                ),
                (
                    "order_number",
                    models.CharField(
                        editable=False,
                        help_text="Atomic unique order number (format: #Eg-00001)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "shipping_address_snapshot",
                    models.TextField(blank=True, help_text="Shipping address copied from Customer at order time"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("CONFIRMED", "Confirmed"),
                            ("SHIPPED", "Shipped"),
                            ("VOIDED", "Voided"),
                        ],
                        default="DRAFT",
                        help_text="Order status (Draft → Confirmed → Shipped → Voided)",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("PARTIALLY_PAID", "Partially Paid"), ("PAID", "Paid")],
                        default="PENDING",
                        help_text="Payment status (Pending, Partially Paid, Paid)",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("COD", "Cash on Delivery"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("CREDIT_CARD", "Credit Card"),
                        ],
                        help_text="Payment method (COD, Bank Transfer, Credit Card)",
                        max_length=20,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Amount paid so far (for partial payment tracking)",
                        max_digits=19,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        editable=False,
                        help_text="Order subtotal (sum of line item totals)",
                        max_digits=19,
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        editable=False,
                        help_text="Tax amount",
                        max_digits=19,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        editable=False,
                        help_text="Order total (subtotal + tax)",
                        max_digits=19,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="Order creation timestamp")),
                ("confirmed_at", models.DateTimeField(blank=True, help_text="Order confirmation timestamp", null=True)),
                ("shipped_at", models.DateTimeField(blank=True, help_text="Order shipped timestamp", null=True)),
                ("voided_at", models.DateTimeField(blank=True, help_text="Order voided timestamp", null=True)),
                ("notes", models.TextField(blank=True, help_text="Internal notes about this order", null=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Employee who confirmed this order",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_orders_confirmed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Employee who created this order",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_orders_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer who placed this order",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="sales.customer",
                    ),
                ),
                (
                    "shipped_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Employee who marked this order as shipped",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_orders_shipped",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Employee who voided this order",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_orders_voided",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Order",
                "verbose_name_plural": "Sales Orders",
                "db_table": "sales_orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date/time when the record was created"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, help_text="Date/time when the record was last modified"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, help_text="Date/time when the record was soft-deleted", null=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name (e.g., 'Corporate', 'Retail')", max_length=100, unique=True
                    ),
                ),
                ("code", models.SlugField(blank=True, help_text="Auto-generated slug code", unique=True)),
                ("description", models.TextField(blank=True, help_text="Category description", null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent category (for hierarchical structure)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="sales.customercategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Category",
                "verbose_name_plural": "Customer Categories",
                "db_table": "sales_customer_categories",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="category",
            field=models.ForeignKey(
                help_text="Customer category/segment",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customers",
                to="sales.customercategory",
            ),
        ),
        migrations.CreateModel(
            name="SalesOrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date/time when the record was created"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, help_text="Date/time when the record was last modified"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, help_text="Date/time when the record was soft-deleted", null=True),
                ),
                ("quantity", models.DecimalField(decimal_places=4, help_text="Quantity ordered", max_digits=19)),
                (
                    "snapshot_unit_price",
                    models.DecimalField(
                        decimal_places=4, help_text="Unit price frozen at order time (19,4 precision)", max_digits=19
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=4,
                        editable=False,
                        help_text="Line total (quantity × snapshot_unit_price)",
                        max_digits=19,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Line item notes", null=True)),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Parent sales order",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.salesorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product being ordered",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_order_items",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Order Item",
                "verbose_name_plural": "Sales Order Items",
                "db_table": "sales_order_items",
                "ordering": ["order", "id"],
                "indexes": [models.Index(fields=["order", "product"], name="sales_order_order_i_0e48aa_idx")],
            },
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(fields=["order_number"], name="sales_order_order_n_51d36c_idx"),
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(fields=["customer", "-created_at"], name="sales_order_custome_9918ba_idx"),
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(fields=["status", "-created_at"], name="sales_order_status_d594c3_idx"),
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(fields=["payment_status", "-created_at"], name="sales_order_payment_c9b819_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["name"], name="sales_custo_name_dfc29e_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["email"], name="sales_custo_email_d108a4_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["category", "name"], name="sales_custo_categor_67fda3_idx"),
        ),
    ]
