# Generated by Django 4.2.29 on 2026-04-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_slug_unique_and_remove_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="slug",
            field=models.SlugField(blank=True, help_text="URL-friendly slug (auto-generated from name)", unique=True),
        ),
        migrations.AlterField(
            model_name="customercategory",
            name="slug",
            field=models.SlugField(blank=True, help_text="URL-friendly slug code", unique=True),
        ),
    ]
